import Foundation
import Testing
@testable import Ghostty

struct AgentSessionTests {
    // MARK: - SessionStatus

    @Test func sessionStatusHasAllCases() {
        // Verify all cases exist and are distinct.
        let running: SessionStatus = .running
        let exited: SessionStatus = .exited
        let completed: SessionStatus = .completed
        let error: SessionStatus = .error(exitCode: 1)
        let killed: SessionStatus = .killed

        // Use if-case to confirm each case pattern-matches correctly.
        if case .running = running {} else { Issue.record("expected .running") }
        if case .exited = exited {} else { Issue.record("expected .exited") }
        if case .completed = completed {} else { Issue.record("expected .completed") }
        if case .error = error {} else { Issue.record("expected .error") }
        if case .killed = killed {} else { Issue.record("expected .killed") }
    }

    @Test func sessionStatusIsAlive() {
        #expect(SessionStatus.running.isAlive == true)
        #expect(SessionStatus.exited.isAlive == false)
        #expect(SessionStatus.completed.isAlive == false)
        #expect(SessionStatus.error(exitCode: 1).isAlive == false)
        #expect(SessionStatus.killed.isAlive == false)
    }

    @Test func sessionStatusEquatable() {
        #expect(SessionStatus.running == .running)
        #expect(SessionStatus.error(exitCode: 1) == .error(exitCode: 1))
        #expect(SessionStatus.error(exitCode: 1) != .error(exitCode: 2))
        #expect(SessionStatus.completed != .exited)
    }

    // MARK: - SessionIndicatorState

    @Test func indicatorStatePriority() {
        // Error is highest priority, inactive is lowest.
        let states: [SessionIndicatorState] = [
            .inactive, .processing, .error, .waiting, .idle, .longRunning, .needsAttention,
        ]
        let sorted = states.sorted()
        #expect(sorted == [.inactive, .idle, .processing, .longRunning, .waiting, .needsAttention, .error])
    }

    @Test func needsAttentionPriorityHigherThanWaiting() {
        #expect(SessionIndicatorState.needsAttention > SessionIndicatorState.waiting)
    }

    @Test func needsAttentionPriorityLowerThanError() {
        #expect(SessionIndicatorState.needsAttention < SessionIndicatorState.error)
    }

    // MARK: - AgentSession Init

    @Test func sessionInitStoresAllFields() {
        let templateId = AgentTemplate.shell.id
        let projectId = UUID()

        let session = AgentSession(
            name: "Shell — MyProject",
            templateId: templateId,
            projectId: projectId
        )

        #expect(session.name == "Shell — MyProject")
        #expect(session.templateId == templateId)
        #expect(session.projectId == projectId)
    }

    @Test func sessionIdIsAutoGenerated() {
        let session1 = AgentSession(name: "A", templateId: UUID(), projectId: UUID())
        let session2 = AgentSession(name: "B", templateId: UUID(), projectId: UUID())
        #expect(session1.id != session2.id)
    }

    @Test func sessionMemberwiseInitDefaultsLastActiveAtToNil() {
        let session = AgentSession(
            name: "Test",
            templateId: UUID(),
            projectId: UUID()
        )
        #expect(session.lastActiveAt == nil)
    }

    // MARK: - Codable

    @Test func sessionCodableRoundTrip() throws {
        let original = AgentSession(
            name: "Claude Code — Test",
            templateId: AgentTemplate.claudeCode.id,
            projectId: UUID()
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(AgentSession.self, from: data)

        #expect(decoded.id == original.id)
        #expect(decoded.name == original.name)
        #expect(decoded.templateId == original.templateId)
        #expect(decoded.projectId == original.projectId)
    }

    @Test func sessionCodableRoundTripPreservesLastActiveAt() throws {
        let timestamp = Date(timeIntervalSince1970: 1_700_000_000)
        let original = AgentSession(
            name: "Active Session",
            templateId: AgentTemplate.claudeCode.id,
            projectId: UUID(),
            sortOrder: 3,
            lastActiveAt: timestamp
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(AgentSession.self, from: data)

        #expect(decoded.lastActiveAt == timestamp)
        #expect(decoded == original)
    }

    @Test func sessionDecodingWithoutLastActiveAtDefaultsToNil() throws {
        // Simulates a legacy workspace.json where sessions predate the lastActiveAt field.
        let projectId = UUID()
        let templateId = AgentTemplate.shell.id
        let id = UUID()
        let json = """
        {
            "id": "\(id.uuidString)",
            "name": "Legacy Session",
            "templateId": "\(templateId.uuidString)",
            "projectId": "\(projectId.uuidString)"
        }
        """
        let data = Data(json.utf8)
        let decoded = try JSONDecoder().decode(AgentSession.self, from: data)

        #expect(decoded.id == id)
        #expect(decoded.name == "Legacy Session")
        #expect(decoded.lastActiveAt == nil)
        #expect(decoded.sortOrder == nil)
    }

    @Test func sessionDecodingWithoutGhostCharacterDefaultsToNil() throws {
        // Simulates a legacy workspace.json where sessions predate the per-session
        // ghost system — must load without error, ghostCharacter defaults to nil.
        let projectId = UUID()
        let templateId = AgentTemplate.shell.id
        let id = UUID()
        let json = """
        {
            "id": "\(id.uuidString)",
            "name": "Legacy Session",
            "templateId": "\(templateId.uuidString)",
            "projectId": "\(projectId.uuidString)"
        }
        """
        let data = Data(json.utf8)
        let decoded = try JSONDecoder().decode(AgentSession.self, from: data)

        #expect(decoded.ghostCharacter == nil)
        // A nil ghostCharacter must still resolve to a valid ghost — no crash.
        #expect(GhostCharacter.allCases.contains(decoded.resolvedGhostCharacter))
    }

    /// FIX 2 (the actual bug): `resolvedGhostCharacter`'s fallback must be
    /// STABLE for a known UUID — not re-rolled per process. Swift's
    /// `Hasher`/`UUID.hashValue` is randomly re-seeded every launch, so the
    /// old implementation (`abs(id.hashValue) % count`) produced a different
    /// index across launches for the identical UUID. The byte-derived
    /// fallback must produce the SAME ghost for the SAME UUID, computed twice
    /// independently in this one process (a stand-in for "across launches",
    /// since the byte derivation has no process-lifetime state to vary).
    @Test func resolvedGhostCharacterFallbackIsStableForKnownUUID() throws {
        let knownId = UUID(uuidString: "E621E1F8-C36C-495A-93FC-0C247A3E6E5F")!
        let projectId = UUID()
        let templateId = AgentTemplate.shell.id

        let sessionA = AgentSession(id: knownId, name: "A", templateId: templateId, projectId: projectId)
        let sessionB = AgentSession(id: knownId, name: "A", templateId: templateId, projectId: projectId)

        #expect(sessionA.ghostCharacter == nil)
        #expect(sessionA.resolvedGhostCharacter == sessionB.resolvedGhostCharacter)

        // Known-input → known-output: pins the exact byte-derivation against a
        // literal independently computed for this UUID, so a future accidental
        // change to the algorithm is caught — comparing the function to itself
        // (as the two lines above do) would move in lockstep with any change
        // to the derivation and never catch a regression.
        #expect(AgentSession.deterministicFallbackGhost(for: knownId) == .fang)
    }

    /// `abs(Int.min)` traps — the old hashValue-based fallback was one bad
    /// hash away from a crash. The byte-derived fallback never calls
    /// `hashValue` at all, so this must simply not crash for any UUID,
    /// including the all-zero / all-max edge cases.
    @Test func deterministicFallbackGhostNeverTrapsOnEdgeUUIDs() {
        let allZero = UUID(uuidString: "00000000-0000-0000-0000-000000000000")!
        let allF = UUID(uuidString: "FFFFFFFF-FFFF-FFFF-FFFF-FFFFFFFFFFFF")!
        _ = AgentSession.deterministicFallbackGhost(for: allZero)
        _ = AgentSession.deterministicFallbackGhost(for: allF)
    }

    @Test func sessionCodableRoundTripPreservesGhostCharacter() throws {
        let original = AgentSession(
            name: "Ghosted Session",
            templateId: AgentTemplate.claudeCode.id,
            projectId: UUID(),
            ghostCharacter: .wraith
        )

        let data = try JSONEncoder().encode(original)
        let decoded = try JSONDecoder().decode(AgentSession.self, from: data)

        #expect(decoded.ghostCharacter == .wraith)
        #expect(decoded.resolvedGhostCharacter == .wraith)
    }

    @Test func sessionDecodingMalformedLastActiveAtThrows() {
        // A string where a numeric/date is expected should fail loudly rather than
        // silently becoming nil. Protects against over-use of `try?` in the decoder.
        let projectId = UUID()
        let templateId = AgentTemplate.shell.id
        let id = UUID()
        let json = """
        {
            "id": "\(id.uuidString)",
            "name": "Bad Session",
            "templateId": "\(templateId.uuidString)",
            "projectId": "\(projectId.uuidString)",
            "lastActiveAt": "not-a-date"
        }
        """
        let data = Data(json.utf8)
        #expect(throws: DecodingError.self) {
            _ = try JSONDecoder().decode(AgentSession.self, from: data)
        }
    }

    // MARK: - Hashable

    @Test func sessionHashableUsesAllFields() {
        // AgentSession uses Swift's synthesized Hashable, which hashes ALL stored
        // properties — not just `id`. Two sessions with the same id but different
        // names or templateIds are treated as distinct values by Set/Dictionary.
        let id = UUID()
        let templateId = UUID()
        let projectId = UUID()

        // Identical fields → same hash → deduplicated.
        let session1 = AgentSession(id: id, name: "A", templateId: templateId, projectId: projectId)
        let session2 = AgentSession(id: id, name: "A", templateId: templateId, projectId: projectId)
        let deduped: Set<AgentSession> = [session1, session2]
        #expect(deduped.count == 1)

        // Different name → different hash → both kept.
        let session3 = AgentSession(id: id, name: "B", templateId: templateId, projectId: projectId)
        let distinct: Set<AgentSession> = [session1, session3]
        #expect(distinct.count == 2)
    }
}
