#!/bin/bash
set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
# Marketing-capture rig — real screenshots of the app for ghostties.org
#
# Builds the app + UI test bundle, runs MarketingCaptureUITests (four
# states: Sessions/Projects tabs x light/dark, each behind the
# GHOSTTIES_CAPTURE_FIXTURE fixture — see CaptureFixture.swift), copies
# the resulting 2x window PNGs out of the sandboxed test runner's temp
# container, converts each to WebP, and emits a <picture> source
# snippet. Re-runnable and idempotent — every output path is
# overwritten in place, nothing accumulates.
#
# Usage: bash scripts/capture-marketing.sh
# ─────────────────────────────────────────────────────────────────────

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MACOS_DIR="$REPO_ROOT/macos"
DERIVED_DATA="$MACOS_DIR/build"
OUT_DIR="$REPO_ROOT/docs/design/web-redesign/captures"

STATES=(sessions-light sessions-dark projects-light projects-dark)

mkdir -p "$OUT_DIR"

echo "==> Building Ghostties + GhosttyUITests (Debug, arm64)"
xcodebuild build-for-testing \
    -project "$MACOS_DIR/Ghostties.xcodeproj" \
    -scheme Ghostties \
    -destination 'platform=macOS' \
    -derivedDataPath "$DERIVED_DATA" \
    ONLY_ACTIVE_ARCH=YES ARCHS=arm64

echo "==> Running MarketingCaptureUITests (4 states)"
TEST_LOG="$(mktemp)"
trap 'rm -f "$TEST_LOG"' EXIT

xcodebuild test-without-building \
    -project "$MACOS_DIR/Ghostties.xcodeproj" \
    -scheme Ghostties \
    -destination 'platform=macOS' \
    -only-testing:GhosttyUITests/MarketingCaptureUITests \
    -derivedDataPath "$DERIVED_DATA" \
    ONLY_ACTIVE_ARCH=YES ARCHS=arm64 \
    2>&1 | tee "$TEST_LOG"

# The test prints one "CAPTURE_OUTPUT: <path>" line per state to stdout,
# pointing at a PNG inside the UI test runner's own sandboxed temp
# container (it cannot write to an arbitrary host path — see
# MarketingCaptureUITests.swift). Copy each one out.
echo "==> Copying captures out of the sandboxed test container"
CAPTURE_PATHS="$(grep '^CAPTURE_OUTPUT: ' "$TEST_LOG" | sed 's/^CAPTURE_OUTPUT: //')"
if [ -z "$CAPTURE_PATHS" ]; then
    echo "error: no CAPTURE_OUTPUT lines found in test output — did the tests run?" >&2
    exit 1
fi

while IFS= read -r src; do
    name="$(basename "$src" .png)"
    dest="$OUT_DIR/app-${name}@2x.png"
    cp "$src" "$dest"
    echo "  $dest"
done <<< "$CAPTURE_PATHS"

# Verify every expected state landed — a partial run (e.g. one test
# failed) should fail loudly, not silently ship three of four states.
for state in "${STATES[@]}"; do
    if [ ! -f "$OUT_DIR/app-${state}@2x.png" ]; then
        echo "error: missing capture for '$state' — expected $OUT_DIR/app-${state}@2x.png" >&2
        exit 1
    fi
done

echo "==> Converting to WebP"
if ! command -v cwebp &>/dev/null; then
    echo "error: cwebp not found — install with 'brew install webp'" >&2
    exit 1
fi

for state in "${STATES[@]}"; do
    png="$OUT_DIR/app-${state}@2x.png"
    webp="$OUT_DIR/app-${state}@2x.webp"
    cwebp -quiet -q 90 "$png" -o "$webp"
    echo "  $webp"
done

echo "==> Writing <picture> source snippet"
SNIPPET_FILE="$OUT_DIR/picture-snippet.html"
cat > "$SNIPPET_FILE" <<'EOF'
<!-- Generated by scripts/capture-marketing.sh — do not hand-edit.
     Swap <picture> for whichever single state a given layout needs,
     or keep all four and toggle visibility with the site's own
     light/dark + Sessions/Projects state. Paths are relative to this
     file (docs/design/web-redesign/captures/). -->

<picture data-app-state="sessions" data-app-theme="light">
  <source srcset="app-sessions-light@2x.webp" type="image/webp">
  <img src="app-sessions-light@2x.png" alt="Ghostties Sessions tab, light mode" width="1280" height="705">
</picture>

<picture data-app-state="sessions" data-app-theme="dark">
  <source srcset="app-sessions-dark@2x.webp" type="image/webp">
  <img src="app-sessions-dark@2x.png" alt="Ghostties Sessions tab, dark mode" width="1280" height="705">
</picture>

<picture data-app-state="projects" data-app-theme="light">
  <source srcset="app-projects-light@2x.webp" type="image/webp">
  <img src="app-projects-light@2x.png" alt="Ghostties Projects tab, light mode" width="1280" height="705">
</picture>

<picture data-app-state="projects" data-app-theme="dark">
  <source srcset="app-projects-dark@2x.webp" type="image/webp">
  <img src="app-projects-dark@2x.png" alt="Ghostties Projects tab, dark mode" width="1280" height="705">
</picture>
EOF
echo "  $SNIPPET_FILE"

echo "==> Done"
ls -la "$OUT_DIR"
